//
//  UIColor+SDAdditions.swift
//
//  Generated by Zeplin on 7/16/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
    class var sdTangerine: UIColor {
        return UIColor(red: 255.0 / 255.0, green: 140.0 / 255.0, blue: 0.0, alpha: 1.0)
    }

    class var sdButterscotch: UIColor {
        return UIColor(red: 255.0 / 255.0, green: 182.0 / 255.0, blue: 81.0 / 255.0, alpha: 1.0)
    }

    class var sdDarkTaupe: UIColor {
        return UIColor(red: 98.0 / 255.0, green: 61.0 / 255.0, blue: 61.0 / 255.0, alpha: 1.0)
    }

    class var sdPaleGrey: UIColor {
        return UIColor(red: 242.0 / 255.0, green: 244.0 / 255.0, blue: 245.0 / 255.0, alpha: 1.0)
    }

    class var sdSunflowerYellow: UIColor {
        return UIColor(red: 255.0 / 255.0, green: 219.0 / 255.0, blue: 0.0, alpha: 1.0)
    }

    class var sdBrightBlue: UIColor {
        return UIColor(red: 0.0, green: 122.0 / 255.0, blue: 255.0 / 255.0, alpha: 1.0)
    }

    class var sdNeonRed: UIColor {
        return UIColor(red: 255.0 / 255.0, green: 0.0, blue: 72.0 / 255.0, alpha: 1.0)
    }

    class var sdSilver: UIColor {
        return UIColor(red: 206.0 / 255.0, green: 210.0 / 255.0, blue: 213.0 / 255.0, alpha: 1.0)
    }
    
    class var sdBrownishGrey: UIColor { 
        return UIColor(white: 104.0 / 255.0, alpha: 1.0)
    }

    class var sdMudBrown12: UIColor {
        return UIColor(red: 80.0 / 255.0, green: 53.0 / 255.0, blue: 21.0 / 255.0, alpha: 0.12)
    }
}

// Text styles

extension UIFont {
    class func sdTextStyle1Font() -> UIFont {
        return UIFont.systemFont(ofSize: 33.0, weight: UIFontWeightLight)
    }

    class var sdTextStyle1_1Font: UIFont {
        return UIFont.systemFont(ofSize: 25.0, weight: UIFontWeightRegular)
    }

    class func sdTextStyle2Font() -> UIFont {
        return UIFont.systemFont(ofSize: 20.0, weight: UIFontWeightMedium)
    }

    class func sdTextStyle3Font() -> UIFont {
        return UIFont.systemFont(ofSize: 17.0, weight: UIFontWeightRegular)
    }

    class var sdTextStyle4Font: UIFont {
        return UIFont.systemFont(ofSize: 14.0, weight: UIFontWeightRegular)
    }

    class var sdTextStyle5Font: UIFont {
        return UIFont.systemFont(ofSize: 10.0, weight: UIFontWeightRegular)
    }


}
